### ISSUE TITLE
bug report: some situations that not compilable

### ISSUE THREAD

**Issue by yportne13** [moonbitlang/moonbit-syntax#12]
i have been post these bugs at [here](https://www.zhihu.com/pin/1658414553833807872) at vscode extension version 0.1.56，but seems that nobody see it. one bug is that:
```go
let x = -1
let y = -x
y.print()
```
no err diagnostic, but not compilable

**Comment by bobzhang** [comment]
thanks for reporting, should be fixed and updated tomorrow
