### ISSUE TITLE
Why local function's keyword is `fn` but not `func`?

### ISSUE THREAD

**Issue by WeZZard** [moonbitlang/moonbit-syntax#9]
There was a question came up while I'm reading the repo: why local function's keyword is `fn` but not `func`?

I guess this brought some simplicity to the implementation of the language. Because a higher order procedure has to capture used local variables and make those local variables to escape if the procedure itself is escaping. This brought differences to the implementation between procedures and higher order procedures. Using two different keywords can clarify the differences between them at the beginning of the source file getting parsed.

But I think the simplicity to the end users of the language is much more important to the simplicity of the language implementation. The end users of the language has not to remember two different keywords when they are doing similar things.

Plus, if the garbage collection algorithm of the language is not automatic reference counting but a Java-like graph-based garbage collection algorithm, differing these two concepts (procedure v.s. higher order procedure) does not make more differences to the end users in their first impression which is compared to using automatic reference counting. Because if the language is using automatic reference counting as its garbage collection algorithm, the end users of the language has to annotate the ownership of the captured variable when they are using high order procedure such that they can avoid retain cycles. But a language using Java-like graph-based garbage collection algorithm does not have such an enforcement.

Of course, all these above are just my guess. It might be wrong. So why this language is using two different keywords to represent function and local function?

**Comment by bobzhang** [comment]
hi @WeZZard , thanks for your interest!

> But I think the simplicity to the end users of the language is much more important to the simplicity of the language implementation. 

Agreed.

Toplevel `func` and local function indeed have different semantics in various respects: type inference, polymorphism and lifetime. It could be made the same syntax (not too hard), this is still in the flux, it might be subject to change in the future.

You are welcome to discuss more in taolun.moonbitlang.com or discuss.moonbiglang.com
